name: Build PHP for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build PHP Binaries for Android
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf bison re2c libxml2-dev libsqlite3-dev libssl-dev libcurl4-openssl-dev pkg-config

      # Download and configure Android NDK
      - name: Setup Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip
          export ANDROID_NDK_HOME=$PWD/android-ndk-r25c
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

      # Configure and build PHP for arm64-v8a
      - name: Build PHP for arm64-v8a
        run: |
          ./buildconf --force
          ./configure --host=aarch64-linux-android --prefix=$PWD/output/arm64-v8a --enable-cli
          make -j$(nproc)
          make install

      # Configure and build PHP for armeabi-v7a
      - name: Build PHP for armeabi-v7a
        run: |
          make clean
          ./configure --host=arm-linux-androideabi --prefix=$PWD/output/armeabi-v7a --enable-cli
          make -j$(nproc)
          make install

      # Upload the binaries as artifacts
      - name: Upload Binaries
        uses: actions/upload-artifact@v3
        with:
          name: php-binaries
          path: output/
