name: Build PHP for Android with ZIP

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build PHP for ${{ matrix.arch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [armv7a, arm64]

    env:
      PHP_VERSION: "8.2.18"
      API_LEVEL: "24"

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up environment variables
      run: |
        if [ "${{ matrix.arch }}" == "arm64" ]; then
          echo "TARGET_HOST=aarch64-linux-android" >> $GITHUB_ENV
          echo "ARCH=arm64-v8a" >> $GITHUB_ENV
        else
          echo "TARGET_HOST=armv7a-linux-androideabi" >> $GITHUB_ENV
          echo "ARCH=armeabi-v7a" >> $GITHUB_ENV
        fi

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential autoconf bison re2c libxml2-dev \
          libsqlite3-dev libssl-dev libcurl4-openssl-dev pkg-config \
          git wget unzip cmake

    - name: Download PHP source
      run: |
        wget https://www.php.net/distributions/php-${PHP_VERSION}.tar.gz
        tar -xf php-${PHP_VERSION}.tar.gz
        mv php-${PHP_VERSION} php-src

    - name: Download Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
        unzip -q android-ndk-r25c-linux.zip
        echo "ANDROID_NDK_HOME=$GITHUB_WORKSPACE/android-ndk-r25c" >> $GITHUB_ENV

    - name: Build libzip for Android
      run: |
        git clone https://github.com/nih-at/libzip.git
        mkdir -p libzip/build && cd libzip/build
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/android-ndk-r25c/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=${ARCH} \
          -DANDROID_PLATFORM=android-${API_LEVEL} \
          -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/deps/libzip \
          -DBUILD_SHARED_LIBS=OFF
        make -j$(nproc)
        make install

    - name: Build PHP
      run: |
        cd php-src
        export TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
        export SYSROOT=$TOOLCHAIN/sysroot

        export CC="$TOOLCHAIN/bin/${TARGET_HOST}${API_LEVEL}-clang"
        export CXX="$TOOLCHAIN/bin/${TARGET_HOST}${API_LEVEL}-clang++"
        export AR="$TOOLCHAIN/bin/llvm-ar"
        export RANLIB="$TOOLCHAIN/bin/llvm-ranlib"
        export LD="$TOOLCHAIN/bin/ld"
        export STRIP="$TOOLCHAIN/bin/llvm-strip"

        export PKG_CONFIG_PATH=$GITHUB_WORKSPACE/deps/libzip/lib/pkgconfig

        ./buildconf --force

        ./configure \
          --host=$TARGET_HOST \
          --prefix=$GITHUB_WORKSPACE/install/${ARCH} \
          --disable-all \
          --enable-cli \
          --enable-mbstring \
          --enable-json \
          --enable-filter \
          --enable-ctype \
          --enable-tokenizer \
          --enable-pdo \
          --with-pdo-sqlite \
          --with-sqlite3 \
          --with-zlib \
          --with-openssl \
          --with-curl \
          --with-libxml \
          --enable-xml \
          --with-zip=$GITHUB_WORKSPACE/deps/libzip \
          CC="$CC" CXX="$CXX" AR="$AR" RANLIB="$RANLIB" LD="$LD" STRIP="$STRIP" \
          --with-sysroot="$SYSROOT"

        make -j$(nproc)
        make install

    - name: Archive PHP binary
      run: |
        cd install/${ARCH}
        zip -r ${{ github.workspace }}/php-${PHP_VERSION}-${ARCH}.zip .

    - name: Upload binary to release
      uses: softprops/action-gh-release@v2
      with:
        files: php-${{ env.PHP_VERSION }}-${{ env.ARCH }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
